var searchData=
[
  ['vcoroutineschedule_0',['vCoRoutineSchedule',['../group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete_1',['vQueueDelete',['../group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary_2',['vSemaphoreCreateBinary',['../group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphoredelete_3',['vSemaphoreDelete',['../group__vSemaphoreDelete.html',1,'']]],
  ['vstreambufferdelete_4',['vStreamBufferDelete',['../group__vStreamBufferDelete.html',1,'']]],
  ['vtaskdelay_5',['vTaskDelay',['../group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil_6',['vTaskDelayUntil',['../group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete_7',['vTaskDelete',['../group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler_8',['vTaskEndScheduler',['../group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetinfo_9',['vTaskGetInfo',['../group__vTaskGetInfo.html',1,'']]],
  ['vtaskgetruntimestats_10',['vTaskGetRunTimeStats',['../group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist_11',['vTaskList',['../group__vTaskList.html',1,'']]],
  ['vtaskpriorityset_12',['vTaskPrioritySet',['../group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume_13',['vTaskResume',['../group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr_14',['vTaskResumeFromISR',['../group__vTaskResumeFromISR.html',1,'']]],
  ['vtaskstartscheduler_15',['vTaskStartScheduler',['../group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend_16',['vTaskSuspend',['../group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall_17',['vTaskSuspendAll',['../group__vTaskSuspendAll.html',1,'']]]
];
